[settings]
activate_aggressive = true
always_keep_download = false             # deleted after install by default
always_keep_install = true               # deleted on failure by default
jobs = 4
not_found_auto_install = true
env_file = '.env'
asdf_compat = true                       # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
http_timeout = '10'                      # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
atuin = { version = "latest", os = ["linux"] }
ripgrep = { version = "latest", os = ["linux"] }
eza = { version = "latest", os = ["linux"] }
zoxide = { version = "latest", os = ["linux"] }
jq = { version = "latest", os = ["linux"] }
yq = { version = "latest", os = ["linux"] }
github-cli = { version = "latest", os = ["linux"] }
kubectx = { version = "latest", os = ["macos"] }
kubens = { version = "latest", os = ["macos"] }
usage = 'latest'
node = 'lts'
"npm:ccstatusline" = 'latest'
