[settings]
activate_aggressive = true
always_keep_download = false             # deleted after install by default
always_keep_install = true               # deleted on failure by default
jobs = 4
not_found_auto_install = true
env_file = '.env'
asdf_compat = true                       # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
http_timeout = '10'                      # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
experimental = true
idiomatic_version_file_enable_tools = []

[tools]
node = '22'
helmfile = '1.1.9'
kustomize = '5.8.0'
kubectx =  '0.9.5'
kubens = '0.9.5'
