dialect = "uk"

auto_sync = false
update_check = false

search_mode = "fuzzy"
style = "compact"
invert = false
inline_height = 10
show_preview = true
show_help = false
show_tabs = false

secrets_filter = true

local_timeout = 1
enter_accept = false

[dotfiles]
enabled = false

[sync]
records = true
