git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium --oneline
  log:
    showGraph: always
    showWholeGraph: true
gui:
  expandFocusedSidePanel: true
os:
  edit: "nvim"
customCommands: []